---
name: Snapshot Test
on:
  workflow_call:
    inputs:
      xtest_version:
        type: string
        default: v0.2.4
      crossplane_version:
        type: string
        default: v2.3.4

jobs:
  snapshot-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install deps
        run: >
          sudo apt-get update
          && sudo apt-get install -y --no-install-recommends
          ca-certificates
          curl
          make
          && sudo rm -rf /var/lib/apt/lists/*

      - name: Install oras
        uses: oras-project/setup-oras@v1

      - name: Install xtest
        run: |
          TMP="$(mktemp -d)"
          oras pull ghcr.io/sn-atmos/xtest_linux_x86_64:${{ inputs.xtest_version }} -o "$TMP"
          cp "$TMP/xtest" /usr/local/bin/xtest
          chmod +x /usr/local/bin/xtest
          rm -rf "$TMP"

      - name: Install Crossplane binary
        run: >
          curl -sSfo /usr/local/bin/crossplane-bin
          https://releases.crossplane.io/stable/${{ inputs.crossplane_version }}/bin/linux_amd64/crossplane
          && chmod +x /usr/local/bin/crossplane-bin

      - name: Test
        run: |
          make test

      - name: Cache crossplane package schemas
        uses: actions/cache@v5
        with:
          path: ~/.crossplane/cache
          key: crossplane-cache

      - name: Cache xtest package schemas
        uses: actions/cache@v5
        with:
          path: ~/.cache/xtest
          key: xtest-cache

      - name: Validate
        continue-on-error: true
        run: |
          make validate
